/// <reference path="../pb_data/types.d.ts" />

// sku + title stay; sku is auto-generated by the defaults hook, so it must not be
// API-required (volunteers create items without sending a SKU).

migrate(
  (db) => {
    const dao = new Dao(db);
    const items = dao.findCollectionByNameOrId('items');
    const sku = items.schema.getFieldByName('sku');
    if (sku) {
      sku.required = false;
      dao.saveCollection(items);
    }
  },
  (db) => {
    const dao = new Dao(db);
    const items = dao.findCollectionByNameOrId('items');
    const sku = items.schema.getFieldByName('sku');
    if (sku) {
      sku.required = true;
      dao.saveCollection(items);
    }
  },
);
